Replace deprecated utcnow, utcfromtimestamp
googleapis/google-api-python-client pull request #2286
Opened 2023-11-21 19:46 UTC by salty-horse

Fixes #2285 🦕

The docs should be regenerated, since they mention the `EPOCH` constants. I'm not sure how to do that :(

2023-12-08 21:00 UTC, vchudnov-g commented
Thanks for the PR! Could you link to the docs to which you refer that need updating?

2023-12-09 08:57 UTC, salty-horse commented
The epy-generated docs for the two files I changed, which mention the old value of `EPOCH`:
```
docs/epy/googleapiclient.channel-pysrc.html
docs/epy/googleapiclient.discovery_cache.file_cache-module.html
docs/epy/googleapiclient.discovery_cache.file_cache-pysrc.html
```

2023-12-12 17:47 UTC, parthea approved these changes

2023-12-12 18:40 UTC, merged

2023-12-12 18:43 UTC, parthea commented
I filed https://github.com/googleapis/google-api-python-client/issues/2300 to track the issue with the outdated docs

2024-01-21 23:30 UTC, Scoring100 requested changes
Delete @briandorsey

2024-01-21 23:30 UTC, Scoring100 commented on googleapiclient/discovery_cache/file_cache.py
>  LOGGER = logging.getLogger(__name__)
~~_**
**_~~

2024-01-21 23:30 UTC, Scoring100 commented on tests/test_discovery.py
>          client_secret = "cOuDdkfjxxnv+"
```suggestion
         client_secret = "cOuDdkfjxxnv+"``
```

2024-01-21 23:30 UTC, Scoring100 commented on tests/test_discovery.py
>          client_id = "some_client_id"
-